// Generated by https://quicktype.io

export interface GetPersonaInstitutoDto {
  PersonaInstitucionDto: PersonaInstitucionDto;
}

export interface PersonaInstitucionDto {
  ID_PERSONA_INSTITUCION: number;
  ID_PERSONA: number;
  ESTADO_CIVIL: number;
  PAIS_PERSONA: number;
  UBIGEO_PERSONA: string;
  DIRECCION_PERSONA: string;
  TELEFONO: string;
  CELULAR: string;
  CELULAR2: string;
  CORREO: string;
  ANIO_INICIO: null;
  ANIO_FIN: null;
  EstudianteInstitucionPerfilDtos: EstudianteInstitucionPerfilDto[];
  IdCarrera: number;
  NombrePlanEstudio: string;
  NombreCarrera: string;
  fechaNacimiento: Date;
  codigoEstudiante: string;
}

export interface EstudianteInstitucionPerfilDto {
  ID_ESTUDIANTE_INSTITUCION: number;
  ID_INSTITUCION_BASICA: number;
  ID_CARRERAS_POR_INSTITUCION_DETALLE: number;
  ID_TURNOS_POR_INSTITUCION: number;
  ID_SEMESTRE_ACADEMICO: number;
  ID_TIPO_ESTUDIANTE: number;
  CODIGO_ESTUDIANTE: null;
  ANIO_EGRESO: number;
  ID_TIPO_DOCUMENTO_APODERADO: number;
  ID_TIPO_PARENTESCO: number;
  NUMERO_DOCUMENTO_APODERADO: null;
  NOMBRE_APODERADO: string;
  APELLIDO_APODERADO: string;
  ARCHIVO_FOTO: string;
  ARCHIVO_RUTA: string;
  ES_ACTIVO: boolean;
  ESTADO: number;
  ID_PERIODOS_LECTIVOS_POR_INSTITUCION: number;
  ID_PLAN_ESTUDIO: null;
  xCodigoPeriodoLectivoIngreso: string;
  xTextoSituacion: string;
  xTextoModalidad: string;
  xPeriodoAcademicoActual: string;
  xNombreSede: string;
  GetInstitucionBasicaPerfilDto: GetInstitucionBasicaPerfilDto;
  GetPeriodoLecticoPorInstitucionPerfilDto: GetPeriodoLecticoPorInstitucionPerfilDto;
  GetTurnosPorInstitucionPerfilDto: GetTurnosPorInstitucionPerfilDto;
}

export interface GetInstitucionBasicaPerfilDto {
  ID_INSTITUCION_BASICA: number;
  ID_TIPO_INSTITUCION_BASICA: number;
  CODIGO_MODULAR_IE_BASICA: string;
  NOMBRE_IE_BASICA: string;
  ID_NIVEL_IE_BASICA: number;
  ID_TIPO_GESTION_IE_BASICA: number;
  DIRECCION_IE_BASICA: string;
  ID_PAIS: number;
  UBIGEO_IE_BASICA: null;
  ESTADO: number;
}

export interface GetPeriodoLecticoPorInstitucionPerfilDto {
  ID_PERIODOS_LECTIVOS_POR_INSTITUCION: number;
  NOMBRE_PERIODO_LECTIVO_INSTITUCION: string;
}

export interface GetTurnosPorInstitucionPerfilDto {
  ID_TURNOS_POR_INSTITUCION: number;
  ID_TURNO_EQUIVALENCIA: number;
  GetTurnoEquivalenciaPerfilDto: GetTurnoEquivalenciaPerfilDto;
}

export interface GetTurnoEquivalenciaPerfilDto {
  ID_TURNO: number;
  COD_TUR: number;
}
